[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["form-data", "node-fetch"]

[functions.process-document]
  memory = 1024
  timeout = 30

[dev]
  publish = "."
  functions = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 